### ISSUE TITLE
zxing你是怎么使用的？

### ISSUE THREAD

**Issue by qq596670409** [wangchenyan/PonyExpress#4]
我google了zxing的资料，发现是直接把android文件夹复制进去，但里面文件和你的很不一样，请指教。

**Comment by wangchenyan** [comment]
快递APP里面使用的zxing是我精简优化过的。

**Comment by qq596670409** [comment]
那我是不是只能够直接把android文件夹放进去使用了

**Comment by wangchenyan** [comment]
@qq596670409 不建议直接使用 google zxing 的代码，太过臃肿，而且很久没有更新，建议在GitHub找下 zxing 的开源库。
